config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'search/search'
  get 'favorites/create'
  get 'favorites/destroy'
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users, controllers: {
    registrations: "users/registrations", sessions: "users/sessions"
  }
  resources :users, only: [:index, :show, :edit, :update]
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  get 'search' => 'searchs#search'

  get 'users/:id/followed' => 'relationships#followed', as: 'followed' # フォロー一覧
  get 'users/:id/follower' => 'relationships#follower', as: 'follower' # フォロワー一覧
  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す

  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  get 'unsubscribe/:name' => 'users#unsubscribe', as: 'confirm_unsubscribe'
  patch ':id/withdraw/:name' => 'users#withdraw', as: 'withdraw_user'
  put 'withdraw/:name' => 'users#withdraw'
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.build(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.save
    render :index
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.find(params[:id])
    @book_comment.destroy
    render :index
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment, :user_id, :book_id)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_error.html.erb
<% if comment.errors.any? %>
  <div class="error_message alert alert-warning">
    <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li class="fas fa-exclamation-triangle"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], url: book_book_comments_path(@book)) do |f| %>
  <%= f.text_area :comment, rows:'5', class:"col" %><br>
  <%= f.submit "送信", class: "comment-submit" %>
<% end %>

app/views/book_comments/_index.html.erb
<% book_comments.each do |book_comment| %>
  <% unless book_comment.id.nil? %>
    <li class="comment-container">
      <div class="comment-box d-flex align-items-center">
        <div class="comment-avatar">
          <%= link_to user_path(book_comment.user) do %>
            <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= book_comment.user.name %><br>
          <% end %>
        </div>
        <div class="comment-text">
          <%= book_comment.comment %>
          <% if book_comment.user == current_user %>
            <%= link_to 'Destroy', book_book_comment_path(book_comment.book.id, book_comment.id), method: :delete, remote: true, class: "btn btn-sm btn-danger" %>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
<% end %>

app/views/book_comments/index.js.erb
$("#comments_area").html("<%= j(render partial: 'index', locals: {book_comments: @book.book_comments}) %>");
$("#error_explanation").html("<%= j(render partial: 'error', locals: {comment: @book_comment}) %>");
$("textarea").val('')